config/routes.rb
Feedbacker::Application.routes.draw do
  
  resources :announcements

  resources :people

  resources :key_datas

  resource :chat_messages

  resources :clients

  resources :hours do
     get :autocomplete_project_name, :on => :collection
  end

  resources :work_categories

  resources :images do
    resources :comments
    resources :surveys do
        resources :questions do
            resources :answers 
        end
    end
  end

  resources :surveys
  
  resources :answers

  resources :assignments

  resources :projects do
    resources :plan_hours
    resources :user_plan_hours
    resources :fixed_costs
  end

  get "home/index"
  
  match 'add_plan_hour' => 'plan_hours#new', :as => :add_plan_hour
  
  match 'comments' => 'comments#new', :as => :comments
  
  match 'accounting' => 'key_datas#index', :as => :accounting
  
  match 'chat'  =>  'chat_messages#index', :as => :chat

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login  
  
  match 'get_user_hours' =>  'hours#show_xml', :as => :get_user_hours
  
  match 'hour_list' =>  'hours#list', :as => :hour_list
  
  match 'hide_announcement' => 'javascripts#hide_announcement', :as => :hide_announcement

  resources :sessions

  resources :users

  root :to => "home#index"

end

app/models/plan_hour.rb
class PlanHour < ActiveRecord::Base
    attr_accessible :amount, :project_id, :work_category_id
    
    validates_presence_of :amount, :project_id, :work_category_id
    
    belongs_to :project
    belongs_to :work_category
    
end

app/controllers/plan_hours_controller.rb
class PlanHoursController < ApplicationController
  def index
    @plan_hours = PlanHour.all
  end

  def show
    @plan_hour = PlanHour.find(params[:id])
  end

  def new
    @plan_hour = PlanHour.new
  end

  def create
    @plan_hour = PlanHour.create!(params[:plan_hour])  
  end

  def edit
    @plan_hour = PlanHour.find(params[:id])
  end

  def update
    @plan_hour = PlanHour.find(params[:id])
    if @plan_hour.update_attributes(params[:plan_hour])
      flash[:notice] = "Successfully updated plan hour."
      redirect_to plan_hour_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @plan_hour = PlanHour.find(params[:id])
    @project = @plan_hour.project
    @plan_hour.destroy
    flash[:notice] = "plan hour deleted."
    redirect_to project_path(@project)
  end

end

app/helpers/plan_hours_helper.rb
module PlanHoursHelper
end

app/views/plan_hours/_form.html.erb
<%= form_for @plan_hour do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </p>
  <p>
    <%= f.label :project_id %><br />
    <%= f.text_field :project_id %>
  </p>
  <p>
    <%= f.label :work_category_id %><br />
    <%= f.text_field :work_category_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/plan_hours/_plan_hour.html.erb
<div class="plan_hour">
	<span class="hours_amout"><%= plan_hour.amount %> hours <span>
	<span class="hours_category"><%= plan_hour.work_category.name %><span>
	<% if current_user.admin? || current_user.project_manager? %>
	 <span class="delete">  <%= link_to "x", project_plan_hour_path(plan_hour.project, plan_hour), :confirm => "delete this plan_hour?", :method => :delete, :title => "delete plan hour" %></span>
	<% end %>
</div>

app/views/plan_hours/create.js.erb
$("#plan_hours").prepend("<%= escape_javascript render(@plan_hour) %>");  
$('#plan_hours_count').html('<%= pluralize(@plan_hour.project.plan_hours.count, "Position") %>');  
$("#plan_hour_amount").val("");
$("#plan_hours").effect("highlight", { color:"#D3ECF4"}, 3000);

app/views/plan_hours/edit.html.erb
<% title "Edit Plan Hour" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @plan_hour %> |
  <%= link_to "View All", plan_hours_path %>
</p>

app/views/plan_hours/index.html.erb
<% title "Plan Hours" %>

<table>
  <tr>
    <th>Amount</th>
    <th>Project</th>
    <th>Work Category</th>
  </tr>
  <% for plan_hour in @plan_hours %>
    <tr>
      <td><%= plan_hour.amount %></td>
      <td><%= plan_hour.project_id %></td>
      <td><%= plan_hour.work_category_id %></td>
      <td><%= link_to "Show", plan_hour %></td>
      <td><%= link_to "Edit", edit_plan_hour_path(plan_hour) %></td>
      <td><%= link_to "Destroy", plan_hour, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Plan Hour", new_plan_hour_path(plan_hour) %></p>

app/views/plan_hours/new.html.erb
<% title "New Plan Hour" %>

<%= render 'form' %>

<p><%= link_to "Back to List", plan_hours_path %></p>

app/views/plan_hours/show.html.erb
<% title "Plan Hour" %>

<p>
  <strong>Amount:</strong>
  <%= @plan_hour.amount %>
</p>
<p>
  <strong>Project:</strong>
  <%= @plan_hour.project_id %>
</p>
<p>
  <strong>Work Category:</strong>
  <%= @plan_hour.work_category_id %>
</p>

<p>
  <%= link_to "Edit", edit_plan_hour_path(@plan_hour) %> |
  <%= link_to "Destroy", @plan_hour, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", plan_hours_path %>
</p>