config/routes.rb
Feedbacker::Application.routes.draw do
  
  resources :announcements

  resources :people

  resources :key_datas

  resource :chat_messages

  resources :clients

  resources :hours do
     get :autocomplete_project_name, :on => :collection
  end

  resources :work_categories

  resources :images do
    resources :comments
    resources :surveys do
        resources :questions do
            resources :answers 
        end
    end
  end

  resources :surveys
  
  resources :answers

  resources :assignments

  resources :projects do
    resources :plan_hours
    resources :user_plan_hours
    resources :fixed_costs
  end

  get "home/index"
  
  match 'add_plan_hour' => 'plan_hours#new', :as => :add_plan_hour
  
  match 'comments' => 'comments#new', :as => :comments
  
  match 'accounting' => 'key_datas#index', :as => :accounting
  
  match 'chat'  =>  'chat_messages#index', :as => :chat

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login  
  
  match 'get_user_hours' =>  'hours#show_xml', :as => :get_user_hours
  
  match 'hour_list' =>  'hours#list', :as => :hour_list
  
  match 'hide_announcement' => 'javascripts#hide_announcement', :as => :hide_announcement

  resources :sessions

  resources :users

  root :to => "home#index"

end

app/models/fixed_cost.rb
class FixedCost < ActiveRecord::Base
    attr_accessible :name, :amount, :project_id
    
    validates_presence_of :amount, :project_id, :name
    
    belongs_to :project
    
end

app/controllers/fixed_costs_controller.rb
class FixedCostsController < ApplicationController
  def index
    @fixed_costs = FixedCost.all
  end

  def show
    @fixed_cost = FixedCost.find(params[:id])
  end

  def new
    @fixed_cost = FixedCost.new
  end

  def create
   @fixed_cost = FixedCost.create!(params[:fixed_cost])  
  end

  def edit
    @fixed_cost = FixedCost.find(params[:id])
  end

  def update
    @fixed_cost = FixedCost.find(params[:id])
    if @fixed_cost.update_attributes(params[:fixed_cost])
      flash[:notice] = "Successfully updated fixed cost."
      redirect_to fixed_cost_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @fixed_cost = FixedCost.find(params[:id])
    @project = @fixed_cost.project
    @fixed_cost.destroy
    flash[:notice] = "Successfully deleted fix costs."
    redirect_to project_path(@project)
  end
end

app/helpers/fixed_costs_helper.rb
module FixedCostsHelper
end

app/views/fixed_costs/_fixed_cost.html.erb
<div class="fixed_cost">
	<span class="cost_amout"><%= number_to_currency(fixed_cost.amount, :unit => "€") %> (<%= fixed_cost.name %>)<span>
	<% if current_user.admin? || current_user.project_manager? %>
	 <span class="delete">  <%= link_to "x", project_fixed_cost_path(fixed_cost.project, fixed_cost), :confirm => "delete this cost?", :method => :delete, :title => "delete cost" %></span>
	<% end %>
</div>

app/views/fixed_costs/_form.html.erb
<%= form_for @fixed_cost do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/fixed_costs/create.js.erb
$("#fixed_costs").prepend("<%= escape_javascript render(@fixed_cost) %>");  
$('#fixed_costs_count').html('<%= pluralize(@fixed_cost.project.fixed_costs.count, "Position") %>');  
$("#fixed_cost_amount").val("");
$("#fixed_cost_name").val("");
$("#fixed_cost").effect("highlight", { color:"#D3ECF4"}, 3000);

app/views/fixed_costs/edit.html.erb
<% title "Edit Fixed Cost" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @fixed_cost %> |
  <%= link_to "View All", fixed_costs_path %>
</p>

app/views/fixed_costs/index.html.erb
<% title "Fixed Costs" %>

<table>
  <tr>
    <th>Name</th>
    <th>Amount</th>
  </tr>
  <% for fixed_cost in @fixed_costs %>
    <tr>
      <td><%= fixed_cost.name %></td>
      <td><%= fixed_cost.amount %></td>
      <td><%= link_to "Show", fixed_cost %></td>
      <td><%= link_to "Edit", edit_fixed_cost_path(fixed_cost) %></td>
      <td><%= link_to "Destroy", fixed_cost, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Fixed Cost", new_fixed_cost_path(fixed_cost) %></p>

app/views/fixed_costs/new.html.erb
<% title "New Fixed Cost" %>

<%= render 'form' %>

<p><%= link_to "Back to List", fixed_costs_path %></p>

app/views/fixed_costs/show.html.erb
<% title "Fixed Cost" %>

<p>
  <strong>Name:</strong>
  <%= @fixed_cost.name %>
</p>
<p>
  <strong>Amount:</strong>
  <%= @fixed_cost.amount %>
</p>

<p>
  <%= link_to "Edit", edit_fixed_cost_path(@fixed_cost) %> |
  <%= link_to "Destroy", @fixed_cost, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", fixed_costs_path %>
</p>