config/routes.rb
Feedbacker::Application.routes.draw do
  
  resources :announcements

  resources :people

  resources :key_datas

  resource :chat_messages

  resources :clients

  resources :hours do
     get :autocomplete_project_name, :on => :collection
  end

  resources :work_categories

  resources :images do
    resources :comments
    resources :surveys do
        resources :questions do
            resources :answers 
        end
    end
  end

  resources :surveys
  
  resources :answers

  resources :assignments

  resources :projects do
    resources :plan_hours
    resources :user_plan_hours
    resources :fixed_costs
  end

  get "home/index"
  
  match 'add_plan_hour' => 'plan_hours#new', :as => :add_plan_hour
  
  match 'comments' => 'comments#new', :as => :comments
  
  match 'accounting' => 'key_datas#index', :as => :accounting
  
  match 'chat'  =>  'chat_messages#index', :as => :chat

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login  
  
  match 'get_user_hours' =>  'hours#show_xml', :as => :get_user_hours
  
  match 'hour_list' =>  'hours#list', :as => :hour_list
  
  match 'hide_announcement' => 'javascripts#hide_announcement', :as => :hide_announcement

  resources :sessions

  resources :users

  root :to => "home#index"

end

app/models/survey.rb
class Survey < ActiveRecord::Base
    attr_accessible :name, :image_id, :questions_attributes
    
    validates_presence_of :name, :image_id
    
    belongs_to :image
    has_many :questions, :dependent => :destroy  
    accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true  
    
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  load_and_authorize_resource :survey
  
  def index
    @surveys = Survey.all
  end

  def show
    @survey = Survey.find(params[:id])
  end

  def new
    @survey = Survey.new
    if params[:image_id]
      @image = Image.find(params[:image_id])
      3.times { @survey.questions.build }  
    else 
      flash[:error] = "You can only create a survey from a image. Go to image/show and then use 'create new client survey'"
      redirect_to root_url
    end
  end

  def create
    @survey = Survey.new(params[:survey])
    if @survey.save
      flash[:notice] = "Successfully created survey."
      redirect_to @survey
    else
      render :action => 'new'
    end
  end

  def edit
    @survey = Survey.find(params[:id])
    @image = @survey.image
  end

  def update
    @survey = Survey.find(params[:id])
    if @survey.update_attributes(params[:survey])
      flash[:notice] = "Successfully updated survey."
      redirect_to survey_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    flash[:notice] = "Successfully destroyed survey."
    redirect_to surveys_url
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_answer.html.erb
<p class="comment_header">
<b><%= link_to answer.user.name, comment.user %> </b>
  <span class="comment_time"><%= time_ago_in_words(answer.created_at) %> ago: 

<% if current_user.admin? || answer.user == current_user %>
   <%= link_to "x", image_survey_question_path(answer.image, answer.survey, answer.question, answer), :confirm => "delete this answer?", :method => :delete, :title => "delete answer" %>
<% end %>

</span>
</p>

<p class="comment_body">
  <%=h answer.content %>
</p>

app/views/surveys/_answer_fields.html.erb
<p id="new_answer" class="add_answer">
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :question_id, :value => q %>
  <%= f.label :content, "your answer" %><br />
  <%= f.text_area :content, :rows => 3, :cols => 25 %>
</p>

<p>
  <%= f.submit "Answer" %>
</p>

app/views/surveys/_form.html.erb
<p>
	<%= image_tag(@image.rendering.url(:small), :border => 0 ) %>
	<span class="myhint">Survey is about this image</span><br/>
	<%= "Image: #{@image.name}"%> <br/>
	<%= "Project: #{@image.project.project_nr} - #{@image.project.name}"%>
<p>
<br/>
<%= nested_form_for @survey do |f| %>  
  <%= f.error_messages %>  
<br/>
  <p>  
    <%= f.label :name %><br />  
    <%= f.text_field :name %>  
<span class="myhint">Title of this survey</span>
	<%= f.hidden_field :image_id, :value => (@survey.new_record? ? @image.id : @survey.image.id) %>
  </p>  
<br/>
  <% f.fields_for :questions do |builder| %>  
  <p>
     <%= builder.hidden_field :survey_id, :value => @survey.id %><br />  
 	 <%= builder.label :content, "Question" %><br />  
 	 <%= builder.text_area :content, :rows => 3 %>  
 	 <%= builder.link_to_remove "remove question" %>
  </p>  
  <% end %>  
 <p><span class="add_question"><%= f.link_to_add "Add question", :questions %> </span></p>
<span class="myhint">You can add as many questions as you want to the survey</span>
<br/>
  <p><%= f.submit "Save survey" %></p>  
<% end %>
<br/>

app/views/surveys/_question_fields.html.erb
<p>
   <%= builder.hidden_field :survey_id, :value => @survey.id %><br />  
	 <%= builder.label :content, "Question" %><br />  
	 <%= builder.text_area :content, :rows => 3 %>  
	 <%= builder.link_to_remove "remove question" %>
</p>

app/views/surveys/edit.html.erb
<% title "Edit Survey" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @survey %> |
  <%= link_to "View All", surveys_path %>
</p>

app/views/surveys/index.html.erb
<% title "Surveys" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for survey in @surveys %>
    <tr>
      <td><%= survey.name %></td>
      <td><%= link_to "Show", survey %></td>
      <td><%= link_to "Edit", edit_survey_path(survey) %></td>
      <td><%= link_to "Destroy", survey, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Survey", new_survey_path(survey) %></p>

app/views/surveys/new.html.erb
<% title "Create client survey" %>

<%= render 'form' %>

<p><%= link_to "Back to Image", image_path(@image) %></p>

app/views/surveys/show.html.erb
<% content_for(:head)  do %>
 <script type="text/javascript" charset="utf-8">
$(document).ready(function () {
		$('.survey .answer_link').each(function () {
			$(this).click(function () {
				$(this).next().next().slideToggle();
			});
		});
	});
 </script>
<% end %>
<% title "Survey for #{@survey.image.name}" %>  
<div class="survey">
<p>
	<%= link_to image_tag(@survey.image.rendering.url(:small), :border => 0 ), @survey.image.rendering.url, :target => "_blank", :title => "click for full size" %>
	<span class="myhint">click image to view in full size</span>
<p>  
  <h2>  <%=h @survey.name %> </h2>  
</p>  
<ol>  
  <% for question in @survey.questions %>  
  <li><%= h question.content %> <a href="#" class="answer_link">answer</a>
	<% qid = question.id %>
	<ul class="answers">
		<% for answer in question.answers %>
		 <li> <%= answer.content %> -- <%= link_to answer.user.name, answer.user %> <span class="grey"><%= answer.created_at.strftime('%B %d at %H:%m')%></span> </li>
		<% end %>  
	</ul>
	<div class="give_answer">
		<% form_for [@survey.image, @survey, question, Answer.new] do |f, question| %>
		 <%= render 'answer_fields', :f => f, :q => qid %>
		<% end %>
	</div>
	</li>  
  <% end %>  
</ol>  
  
<p>  
  <%= link_to "Edit", edit_survey_path(@survey) %> |  
  <%= link_to "Delete Survey", @survey, :confirm => 'Are you sure?', :method => :delete %> |  
  <%= link_to "View All", surveys_path %>  
</p>
</div>