config/routes.rb
Feedbacker::Application.routes.draw do
  
  resources :announcements

  resources :people

  resources :key_datas

  resource :chat_messages

  resources :clients

  resources :hours do
     get :autocomplete_project_name, :on => :collection
  end

  resources :work_categories

  resources :images do
    resources :comments
    resources :surveys do
        resources :questions do
            resources :answers 
        end
    end
  end

  resources :surveys
  
  resources :answers

  resources :assignments

  resources :projects do
    resources :plan_hours
    resources :user_plan_hours
    resources :fixed_costs
  end

  get "home/index"
  
  match 'add_plan_hour' => 'plan_hours#new', :as => :add_plan_hour
  
  match 'comments' => 'comments#new', :as => :comments
  
  match 'accounting' => 'key_datas#index', :as => :accounting
  
  match 'chat'  =>  'chat_messages#index', :as => :chat

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login  
  
  match 'get_user_hours' =>  'hours#show_xml', :as => :get_user_hours
  
  match 'hour_list' =>  'hours#list', :as => :hour_list
  
  match 'hide_announcement' => 'javascripts#hide_announcement', :as => :hide_announcement

  resources :sessions

  resources :users

  root :to => "home#index"

end

app/models/image.rb
class Image < ActiveRecord::Base
    attr_accessible :id, :project_id, :name, :rendering, :user_id
    belongs_to :project                             
    belongs_to :user
    
    validates_presence_of :name
    validates_presence_of :project_id      
    
    has_many :comments, :dependent => :destroy   
    
    has_many :surveys,  :dependent => :destroy  
    accepts_nested_attributes_for :surveys, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true  
    
    
    cattr_reader :per_page
    @@per_page = 5
    
    
    
    #paperclip
     has_attached_file :rendering,
        :styles => {
          :thumb=> "100x100>",
          :small  => "400x400>",
          :big => "850x850>" }
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :login_required

 
  def index
    @images = Image.paginate :page => params[:page], :order => "created_at desc", :per_page => 15
  end

  def new
    @image = Image.new
  end        
  
  def show
    @image = Image.find(params[:id] )
    @comments = @image.comments.order("created_at desc")
  end

  def create
    @image = Image.new(params[:image])
    if @image.save
      flash[:notice] = "Successfully created image."
      redirect_to @image.project
    else
      render :action => 'new'
    end
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    if @image.update_attributes(params[:image])
      flash[:notice] = "Successfully updated image."
      render :action => :show
    else
      render :action => 'edit'
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    flash[:notice] = "Successfully destroyed image."
    redirect_to images_url
  end 
  
  private
                                                     
  def sort_column
    params[:sort] ||= "name"
  end
     
  def sort_direction
    params[:direction] ||= "asc"
  end
  
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_comment_fields.html.erb
<p id="new_comment" class="add_comment">
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :image_id, :value => @image.id %>
  <%= f.label :body, "leave a comment" %><br />
  <%= f.text_area :body, :rows => 5, :cols => 25 %>
</p>

<p>
  <%= f.submit "Add Comment" %>
</p>

app/views/images/_form.html.erb
<% form_for @image,  :html=>{:multipart=>true} do |f| %> 
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :project_id %><br />

	<% if params[:project] %>
	
    <%= collection_select(:image, :project_id, Project.order('project_nr asc'), :id, :name_number, :selected => params[:project]) %>

	<% else %>
	
	   <%= collection_select(:image, :project_id, Project.order('project_nr asc'), :id, :name_number, :prompt => true) %>
	
	<% end %>
  </p>
  <div class="field">
	<p>
	<%= f.label :rendering %><br />
  	<%= f.file_field :rendering%>
	</p>
  </div>
  <p> 
	<%= f.hidden_field :user_id, :value => current_user.id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/images/edit.html.erb
<% title "Edit Image" %>

<% form_for @image,  :html=>{:multipart=>true} do |f| %> 
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :project_id %><br />
    <%= collection_select(:image, :project_id, Project.all, :id, :name, :prompt => true) %>
  </p>  
  <p>
    <%=link_to image_tag(@image.rendering.url(:thumb), :border => 0 ), @image, :title => @image.name %>    
  </p>
  <div class="field">
	<p>
	<%= f.label :rendering %><br />
  	<%= f.file_field :rendering%>
	</p>
  </div>
  <p><%= f.submit %></p> 

<% end %>
<br/>
<p>
	<%= link_to "go back", :back %>
</p>

app/views/images/index.html.erb
<% title "Images" %>

<table>
  <tr>
	<th>Preview</th>
    <th><%= "Name" %></th>
    <th><%= "Project" %></th>
    <th><%= "Uploaded" %></th> 
    <th>Comments</th> 
  </tr>
  <% for image in @images %>
    <tr class="<%= cycle('white','grey')-%>">           
	  <td> 
	   	<% if image.rendering.exists? then %>
	       	<%= link_to image_tag(image.rendering.url(:thumb), :border => 0 ), image, :title => image.name %>
		<% else %> 
			not available
	   	<% end %>

	   </td>
      <td><%= image.name %></td>
      <td><%= image.project.name if image.project %></td>
      <td><%= image.created_at.to_formatted_s(:long) %></td>
	  <td><%= pluralize(image.comments.count, "comment") %></td>                                          
	  <td><%= link_to "View", image %></td>     
	  <% if image.user == current_user || current_user.admin? %>
      <td><%= link_to "Edit", edit_image_path(image) %></td>  
      <td><%= link_to "Delete", image, :confirm => 'Delete this image?', :method => :delete %></td>
	   
	<% end %>
    </tr>
  <% end %>
</table>
<%= will_paginate @images %> 
<%= page_entries_info @images %>
 
<p><%= link_to "New Image", new_image_path(image) %></p>

app/views/images/new.html.erb
<% title "New Image" %>

<%= render 'form' %>

<p><%= link_to "Back to List", images_path %></p>

app/views/images/show.html.erb
<% title "#{@image.project.name} | #{@image.name}" %>

<% content_for(:head) do %>
<%= stylesheet_link_tag 'jquery-ui-1.8.12.custom', :cache => true %>
<%= javascript_include_tag 'jquery-ui-1.8.12.custom.min', :cache => true %>
<script type="text/javascript"charset="UTF-8">  
var comments = 1;
      $(function () {  
        $('#showhide').click(function () {  
          commentsShowHide();
		});
      });  
    </script>
<% end %>

 <div class="basic_image">
<br/> 
 	<% if @image.rendering.exists? then %>
     	<%= image_tag @image.rendering.url, :width => "850" %>
	<% else %> 
		not available
 	<% end %>
 <br/>       
<table class="pretty">
	<tr>
     <th>Uploaded</th>
     <th>Uploader</th>
     <th>Project</th> 
     <th>HQ</th> 
     <th>Status</th>  
     <th>Client Survey</th>  
	</tr>
	<tr>
	 <td><%= @image.created_at.to_formatted_s(:long) %></td>
	 <td><%= link_to @image.user.name, @image.user %></td>
	 <td><%= link_to @image.project.name.to_s, @image.project %></td>
	 <td><%= link_to "Show / Download", @image.rendering.url %></td>
	 <td>to do</td>
	 <td><%= link_to "create new client survey", new_survey_path(:image_id => @image.id) %>
	</tr>		
 </table>          
</div> 
<div class="newest_images"> 
     <table>
		<tr><th>Other Images of <%= @image.project.name %></th></tr>
		<tr>
		   <td> 	
	<% for img in @image.project.images do %> 
		   <% if img!= @image %>
	      	<%= link_to image_tag(img.rendering.url(:thumb), :border => 0 ), img, :title => img.name %>
		   <% end %> 
	<% end %> 
	
			</td>
	   </tr>
   </table>
</div>
<div class="comments">
  <h2 id="comments_count"><%= pluralize(@image.comments.count, "comment") %><span class="showhide"><a id="showhide" href="#">hide</a></h2>
  <div id="comments">
	<%= render @comments %>
</div>


<% form_for [@image, Comment.new], :remote => true  do |f| %>
 <%= render 'comment_fields', :f => f %>
<% end %>
</div>
<br/>
<p>
  <%= link_to "Edit", edit_image_path(@image) %> |
  <%= link_to "Delete Image", @image, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "All Images", images_path %>
</p>
                         
<br/>
<p>
	<%= link_to "go back", :back %>
</p>